---
title: "Short corn"
subtitle: "update"
author: "Jesse Bealsburg"
date: "`r Sys.Date()`"
format: pdf
editor: visual
execute:
  echo: false
  message: false
  warning: false
editor_options: 
  chunk_output_type: console
---

### Notes

No stage determination data yet due to mistakes with methodology

DKC is the check variety that is not a short stature corn hybrid.

\newpage

#### Figures

```{r}
library(tidyverse)
read.csv("Cor Datasheet - data (4).csv") -> dat

dat %>% 
  select(-stage) %>% 
  rename(plant_height = plant.height..cm.,
         leaf_count = leaf.count,
         stem_circumference = stem.circumference..cm.,
         light = light.penetration,
         node_number = node.number,
         node_tassel_distance = distance.between.node.and.tassel..cm.) %>% 
  mutate(plot = factor(plot),
         date = as.POSIXct(date,
                           format = "%m/%d/%Y"))-> dat
```

```{r}
dat %>% 
  ggplot(aes(date,plant_height,
             col=name)) +
  stat_summary(geom = "line") +
  stat_summary() +
  labs(y="plant height (cm)")
```

\newpage

```{r}
dat %>% 
  ggplot(aes(date,leaf_count,
             col=name)) +
  stat_summary(geom = "line") +
  stat_summary()
```

-   

\newpage

```{r}
dat %>% 
  ggplot(aes(date,stem_circumference,
             col=name)) +
  stat_summary(geom = "line") +
  stat_summary()
```

-   

\newpage

```{r}
dat %>% 
  ggplot(aes(date,node_number,
             col=name)) +
  stat_summary(geom = "line") +
  stat_summary()
```

-   

\newpage

```{r}

dat %>% 
  ggplot(aes(date,node_tassel_distance,
             col=name)) +
  stat_summary(geom = "line") +
  stat_summary() +
  labs(y="distance from 5th node to base of tassel (cm)")
```

-   
