---
title: "Perennial wheat report"
subtitle: "(Pewhe1 + Pewhe2)"
author: "Jesse Bealsburg"
date: today
format: 
  pdf:
    toc: false
editor: visual
execute:
  echo: false
  message: false
  warning: false
editor_options: 
  chunk_output_type: console
---

Jesse's tasks (8Jan2025)

-   Marvin data

    -   Marvining all pewhe 1 (2022,2023,2024) and pewhe 2 (2023,2024),
    -   upload marvin data to pewhe combined
    -   upload TKW for pewhe 2 2024 to OPW fieldbook

-   Threshing data

    -   confirm threshed grain weights, add those to pewhe 2 and pewhe combined

        -   Current theory: 32-1 with hand written tag + 38.5 grams is actually 24-2. This is because hand written envelope is the largest threshed grain weight of entire site-year and Davis guessed it was 32-1, but it's more likely it's from 24-2 because that plot had the highest seedhead weight and one of the highest seedhead counts, yet one of the lowest threshed yields (4.5 grams). The other plots with low harvest efficiency (% of threshed grain recovered from dry seedhead weight) like 12-2 had much lower dry seedhead weights and it's more likely there were just empty seedheads. So if we move handwritten 32-1 to 24-2, we then need to either discard or move the seed in the 24-2 envelope. I think we add it to 24-1. Looking at 24-1 compared with other samples, it looks off. No seed, lots of stem, and that plot also has abnormally low harvest efficiency.

        -   Can we tell differences in how the seeds look between varieties? No. There is way too much variation in both seed size, amount of ergot, amount of hull between plots of the same variety and even within the same plot.

        -   The labeled 32-1 and 32-2 look very similar and the handwritten 32-1 looks very different, so that further supports my hunch of moving that to another plot

    -   convert threshed grain weights to kg ha and add to OPW fieldbook

-   Weed survey data

    -   The 2024 data from 11Jun and 4Jun are in disagreement. Use the yield data to determine which one is correct. It is likely the 4Jun was done incorrectly and 11Jun was done to rememdy it, but the 4Jun data just was not tossed out of dataset and now needs to be tossed.

-   Generate report for Jake

-   PhotoLog

\newpage

# Trial management and specifications

+------------+-------------------------+---------------+---------------+------------------+
| Trial      | Site                    | Planting date | Harvest dates | Termination date |
+============+=========================+===============+===============+==================+
| Pewhe 1    | St Paul - K8            | 2021-09-29    | 18Aug2022,    | 2024-10-11       |
|            |                         |               |               |                  |
|            |                         |               | 13-20Jul2023, |                  |
|            |                         |               |               |                  |
|            |                         |               | 19Jul2024     |                  |
+------------+-------------------------+---------------+---------------+------------------+
| Pewhe 2    | St Paul - Horse Pasture | 2022-09-29    | 12-20Jul2023, | 2024-10-11       |
|            |                         |               |               |                  |
|            |                         |               | 19Jul2024     |                  |
+------------+-------------------------+---------------+---------------+------------------+

: Trial timeline

Weed control was primarily done by hand, especially in Pewhe 2 where the trial was supposed to be organically managed (though a pre-emergent herbicide application did occur by mistake when plants were dormant in early spring). Spot spraying outside of plot areas in alleys to control perennial weeds did occur.

Pest damage typically occurred in early July on early maturing lines. The annual winter wheat checks matured first. On 12Jul2022 and 6Jul2023 in Pewhe 1 and 2 respectively, winter wheat checks were destroyed by pests. Bird and rabbit fencing were used to deter pests during grain ripening and entries were harvested by hand as soon as they were ready, resulting in multiple harvest dates rather than waiting for all entries to fully mature before harvesting.

+------------+-------------+---------------+---------------+------------------------+
| Trial      | 2,4-D       | Pendimethalin | S-metolachlor | Bird netting / fencing |
|            |             |               |               |                        |
|            | (0.5-1pt A) | (2-2.5 pt A)  | (1 pt A)      |                        |
+============+=============+===============+===============+========================+
| Pewhe 1    | 3Oct2022,   | 3May2024,     | 24Apr2024     | 27Jul2022              |
|            |             |               |               |                        |
|            | 24Apr2024   | 13Apr2023     |               |                        |
+------------+-------------+---------------+---------------+------------------------+
| Pewhe 2    |             | 13Apr2023     |               |                        |
+------------+-------------+---------------+---------------+------------------------+

: Crop protection timeline

+--------------+--------------+--------------------------+
| Trial        | 80 kg N A    | 100 kg N                 |
|              |              |                          |
|              | urea         | composted poultry manure |
+==============+==============+==========================+
| Pewhe 1      | 10May2023,   |                          |
|              |              |                          |
|              | 12Apr2024    |                          |
+--------------+--------------+--------------------------+
| Pewhe 2      |              | 19Mar2024                |
+--------------+--------------+--------------------------+

: Fertilizer timeline

| Trial   | Plot length (ft) | Seed per packet (g) |
|---------|------------------|---------------------|
| Pewhe 1 | 15               | 24                  |
| Pewhe 2 | 20               | 25                  |

: Trial layout specs. Both trials planted with Hege 1000 at 1-1.5" depth. Each plot consisted of 4 rows at 12" row spacing, with a 2 ft alley between plots in the same range and a 5 ft alley between ranges. Populations were not controlled for, all plots received the same amount of seed by weight.

\newpage

# Pewhe 1

Pewhe 1 was an unfunded preliminary trial [led by TLI](https://docs.google.com/document/d/1tP9sgS1QMki0SO5UffAFloWDWAFFs2FqxhtA5LTngPw/edit?tab=t.0) with 14 entries and 10 variables.

They said they would provide "robust data sheets and collection protocols", but those never arrived.

In March 2022, standing water over the western edge of the trial caused multiple plots to suffer stand loss. These plots were not dropped from the trial, but the data from them is questionable.

In July 2022, pest damage to plots further degraded confidence in the data quality coming from this trial.

In 2023, many plots lost row definition and the winter wheat checks produced grain yields. This suggests shattering, contamination between plots and contamination within plots of different stand ages.

[Google Site](https://sites.google.com/umn.edu/pewhe1/home) with photos

+-------------------+------------------+
| Entries           | Variables        |
+===================+==================+
| B1107 (21F3827)   | Perenniality     |
|                   |                  |
| OT38 (21F3801)    | Yield, grain     |
|                   |                  |
| Local bread wheat | Seed size        |
|                   |                  |
| 21F4208           | Seed weight      |
|                   |                  |
| 21F3839           | Plant height     |
|                   |                  |
| 21F3803           | Emergence date   |
|                   |                  |
| 21F3805           | Winter hardiness |
|                   |                  |
| 21F3808           | Flowering time   |
|                   |                  |
| 21F3810           | Biomass          |
|                   |                  |
| 21F3814           | Soil moisture    |
|                   |                  |
| 21F3816           |                  |
|                   |                  |
| 21F3820           |                  |
|                   |                  |
| 21F3822           |                  |
+-------------------+------------------+

: Pewhe 1 trial overview. 14 genotypes. 10 measurements.

+------+-------------------+-------------------+----------------+--------------------+-----------------------+-----------------------+-----------------+-------------------+
| year | wet seedheads (g) | dry seedheads (g) | seedhead count | threshed grain (g) | combine yield wet (g) | combine yield dry (g) | straw yield (g) | marvin seed specs |
+======+===================+===================+================+====================+=======================+=======================+=================+===================+
| 2022 | NA                | C                 | C              | C                  | NA                    | NA                    | NA              | C                 |
+------+-------------------+-------------------+----------------+--------------------+-----------------------+-----------------------+-----------------+-------------------+
| 2023 | C                 | C                 | C              | C                  | NA                    | NA                    | NA              | C                 |
+------+-------------------+-------------------+----------------+--------------------+-----------------------+-----------------------+-----------------+-------------------+
| 2024 | C                 | C                 | C              | C                  | C                     | C                     | NA              | IP                |
+------+-------------------+-------------------+----------------+--------------------+-----------------------+-----------------------+-----------------+-------------------+

: Pewhe 1 yield data. C = complete, IP = in progress, NA = missing or not available

+-----------+-----------+------------+-----------+---------------------------+
| year      | lodging   | staging    | height    | weed abundance (% visual) |
+===========+===========+============+===========+===========================+
| 2022      | NA        | NA         | NA        | NA                        |
+-----------+-----------+------------+-----------+---------------------------+
| 2023      | 12Jul2023 | 6Jun2023,  | 12Jul2023 | NA                        |
|           |           |            |           |                           |
|           |           | 21Jun2023, |           |                           |
|           |           |            |           |                           |
|           |           | 12Jul2023  |           |                           |
+-----------+-----------+------------+-----------+---------------------------+
| 2024      | 19Jul2024 | 10Jul2024, | 19Jul2024 | C                         |
|           |           |            |           |                           |
|           |           | 19Jul2024  |           |                           |
+-----------+-----------+------------+-----------+---------------------------+

: Pewhe1 plant performance data

+------------+------------------+-----------------+---------------------+--------------------------------+
| year       | winterkill (y/n) | flowering (y/n) | soil moisture (vwc) | harvest quality (acceptable/n) |
+============+==================+=================+=====================+================================+
| 2022       | C                | 16Jun2022       | 16Jul2022           | 18Aug2022                      |
+------------+------------------+-----------------+---------------------+--------------------------------+
| 2023       | NA               | NA              | NA                  | NA                             |
+------------+------------------+-----------------+---------------------+--------------------------------+
| 2024       | NA               | NA              | NA                  | NA                             |
+------------+------------------+-----------------+---------------------+--------------------------------+

: Pewhe 1 bonus plant performance data

## Harvest notes

27Jul2022 = Finished fencing/netting trial. Jesse took yield from poor yield plots at western end that suffered from standing water, then mowed off due to weeds

18Aug2022 = Harvested all remaining plots. If possible, 3x 24" quadrats taken for yield. Otherwise, seedheads selectively pulled for some data that can be used for marvining and storing. Notes were taken on plots with acceptable populations at harvest

13Jul2023 = Plots past dough stage were harvested at 3x 24" quadrat dimensions. 12 plots were not sufficiently ripe for harvest

19Jul2023 = remaining 12 plots reached sufficient maturity for harvest

\newpage

# Pewhe 2

Pewhe 2 was part of the Organic Perennial Wheat (OPW) add-on trial to the OREI grant.

It was led by Leo, who created [this field book](https://docs.google.com/spreadsheets/d/1vlCDt76LDy9gE5Ittj6cTO1AmbZg-eax/edit?gid=520577738#gid=520577738) that outlined the collection of the following variables

+--------------+--------------------------------------------------------------------------+
| Entry        | Variable                                                                 |
+==============+==========================================================================+
| 6004         | Soil (baseline)                                                          |
|              |                                                                          |
| 6005         | Weed survey at flowering (crop vs weed vs bare ground, dominant species) |
|              |                                                                          |
| 6059         | Staging                                                                  |
|              |                                                                          |
| 6061         | Biomass, total aboveground                                               |
|              |                                                                          |
| Winter wheat | Biomass, weed                                                            |
|              |                                                                          |
|              | Grain yield                                                              |
|              |                                                                          |
|              | Yield components (spike count, TGW)                                      |
|              |                                                                          |
|              | Plot photos                                                              |
|              |                                                                          |
|              | Total plot harvest (combine)                                             |
|              |                                                                          |
|              | Total forage harvest (forage harvester)                                  |
+--------------+--------------------------------------------------------------------------+

+------+-------------------+-------------------+----------------+--------------------+-----------------------+-----------------------+-----------------+-------------------+
| year | wet seedheads (g) | dry seedheads (g) | seedhead count | threshed grain (g) | combine yield wet (g) | combine yield dry (g) | straw yield (g) | marvin seed specs |
+======+===================+===================+================+====================+=======================+=======================+=================+===================+
| 2023 | C                 | C                 | C              | C                  | NA                    | NA                    | C               | C                 |
+------+-------------------+-------------------+----------------+--------------------+-----------------------+-----------------------+-----------------+-------------------+
| 2024 | C                 | C                 | C              | C                  | NA                    | NA                    | C               | IP                |
+------+-------------------+-------------------+----------------+--------------------+-----------------------+-----------------------+-----------------+-------------------+

: Pewhe 2 yield data. C = complete, IP = in progress, NA = missing or not available

+----------+-----------+------------+-----------+---------------------------+--------------------+
| year     | lodging   | staging    | height    | weed abundance (% visual) | weed abundance (g) |
+==========+===========+============+===========+===========================+====================+
| 2023     | 12Jul2023 | 6Jun2023,  | 12Jul2023 | 6Jun2023                  | NA                 |
|          |           |            |           |                           |                    |
|          |           | 21Jun2023, |           |                           |                    |
|          |           |            |           |                           |                    |
|          |           | 12Jul2023  |           |                           |                    |
+----------+-----------+------------+-----------+---------------------------+--------------------+
| 2024     | 19Jul2024 | 26Jun2024, | 19Jul2024 | 4Jun2024,                 | 19Jul2024          |
|          |           |            |           |                           |                    |
|          |           | 10Jul2024, |           | 11Jun2024                 |                    |
|          |           |            |           |                           |                    |
|          |           | 19Jul2024  |           |                           |                    |
+----------+-----------+------------+-----------+---------------------------+--------------------+

: Pewhe 2 plant performance data

+------------+--------------+----------------------+----------------------------------------------+
| year       | plant counts | emergence scores (%) | canopy scores (weed vs. crop vs. bareground) |
+============+==============+======================+==============================================+
| 2023       | C            | C                    | C                                            |
+------------+--------------+----------------------+----------------------------------------------+
| 2024       | NA           | NA                   | C                                            |
+------------+--------------+----------------------+----------------------------------------------+

: Pewhe 2 bonus plant performance data

Pewhe 1 and 2 have emergence data 4 weeks after planting

## Harvest notes

12Jul2023 = some plots had high shatterind and/or herbivory

20Jul2023 = some plots were reharvested because they were not sufficiently mature

10Aug2023 = Katherine harvested some lengths of seedheads to give to Prabin/George. The threshed weights were entered into the Master, but this wasn't part of of the data collection for this project.

19Jul2024 = Winter wheat plots were dropped in second production year since they were an annual crop that was not replanted. These plots were tilled up in spring, planted to a cover, and managed for weeds. They remain in the data structure for year 2, but the cells are empty

# Data processing

## Notes

2022 pewhe grain harvest. If okyield=yes, then it was harvested at quadrat dimension specifications. If okyield=no, quadrat dimensions=na. If harvested 27Jul, quadrat dimensions=na. If harvested both 27Jul and 18Aug, harvest date=18Aug. If date/dimensions cannot be inferred from notes, cell is either left empty or na

Some 2022 pewhe harvest data has not been processed yet. Data is missing.

For staging, heights and lodging, I took 1 date from each production year, closest to harvest, for lodging, height and stage. For height and stage, I just reported the average whereas raw data n=5 or n=10.

For pewhe 2, production year 1. If a given plot was harvested twice (i.e. 12Jul and again on 20Jul), the later harvest date and data were used.

converting quadrat dimensions to square meter basis

```{r conversions, include=F}
library(measurements)

conv_multiunit(24*12*3, 
               from = "inch2",
               to = "m2")


conv_multiunit(20*20, 
               from = "inch2",
               to = "m2")


conv_multiunit(40*12,
               from = "inch2",
               to = "m2")

```

For threshing weights, we have 2 measurements for 32-1 and their sum is too large, but there is no missing data. There is one plot where there was no seed after threshing, but this plot also had no seedheads so it's unlikely the weight from the handwritten corresponds to it.

We have the 2024 pewhe 2 threshed grain weights in Master combined, but we are holding off on converting to kg ha and uploading to OPW field book until we can confirm what has occured with this extra sample.
